/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.11.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./ZuperCampaign.types";
import * as _1 from "./ZuperCampaign.client";
import * as _2 from "./ZuperCampaign.message-composer";
import * as _3 from "./ZuperIndex.types";
import * as _4 from "./ZuperIndex.client";
import * as _5 from "./ZuperIndex.message-composer";
export namespace contracts {
  export const ZuperCampaign = {
    ..._0,
    ..._1,
    ..._2
  };
  export const ZuperIndex = {
    ..._3,
    ..._4,
    ..._5
  };
}